### ISSUE TITLE
GPU EfficientNet is weirdly slow

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#101]
```
did inference in 0.28 s
                 Mul : 163       29.18 ms
                 Add : 140       25.53 ms
                 Pow :  98       18.43 ms
               Pad2D :  17       16.97 ms
              Conv2D :  81       14.49 ms
             Sigmoid :  65       10.23 ms
             Reshape : 230        9.94 ms
                 Sub :  49        9.75 ms
           AvgPool2D :  17        5.93 ms
                 Dot :   1        1.06 ms
```

Run with DEBUG=1 for profiling. Conv2D isn't even close to the top in time users.

**Comment by kartik4949** [comment]
working on my local branch to optimized pyopencl code.

**Comment by kartik4949** [comment]
@geohot  we can look in opencl hands on tutorial ,where the author has stated some techniques to optimize mat mul operations.
https://handsonopencl.github.io/

**Comment by marcelbischoff** [comment]
I am new to opencl but a quick google suggests that the bottleneck are the 3N memory operations on Mul and Add. Also couldn't find a hardware-independent acceleration suggestion.

**Comment by ryanneph** [comment]
From my experience optimizing GPU code, most performance comes from coalescing GPU memory read/write. Broadcasting is in direct opposition to coalesced access since it fragments memory addresses and breaks coalescence. In speed critical scenarios, it makes sense to write separate kernels to address the most common forms of broadcasting that can occur, or reorder the broadcasted memory on CPU before sending to the GPU, then reorder the result to undo any temporary broadcasting effects. This means more code though, which strains the _tiny_ feature of tinygrad.

**Comment by dustcollector12** [comment]
quickly from the ranks: If you are going to speed things up, maybe consider opening a new file optgpufast.py. Current implementation for readability and proof of concept, fast implementation for super fast computations. I think this would make testing, debugging and comparison of results way easier. One major benefit would be that a cpu and a slow gpu implementation remain if the fast gpu implementation is temporarily broken for some users.

**Comment by ophello** [comment]
Can you speed up Conv2d by simplifying the multiply formulas using the distributive property?

Line 470 in opsgpu.py:
`B * groups * cin * iy * ix + g * cin * iy * ix + ci * iy * ix + y * ix + x`
Condense this operation to:
`W * (H * (cin * (g * rcout + c) + ci) + y - iy) + x - ix`

Line 471:
`g * rcout * cin * H * W + c * cin * H * W + ci * H * W + (y - IY) * W + (x - IX)`
Condense to:
`IX * (IY * (cin * (B * groups + g) + ci) + y) + x`

Line 475:
`B * groups * rcout * oy * ox + g * rcout * oy * ox + c * oy * ox + Y * ox + X`
Condense to:
`ox * (oy * (rcout * (B * groups + g) + c) + Y) + X`

**Comment by geohot** [comment]
I found those mults don't make much of a difference for speed, compiler gets them. Up to you which is more readable.

Our goal isn't optgpufast, I think there's some obvious reasons why it's slow that we can fix with very few lines.

**Comment by marcelbischoff** [comment]
We don't have OpenCL 2? Because then I could run eg. x,y,c loops in separate kernels. If I start the separate kernels from Python it is slower. We also need a SGEMM contraction of tensor indices.

Anyways if you scale up Conv2D is actually not that slow on a Mac for being the most naive algorithm:
```
testing [(8, 3, 110, 280), (6, 1, 5, 3)]   torch/tinygrad fp: 12.14 / 0.39 ms  bp: 26.35 / 6.21 ms
```
Note you can reorder the loops so it is essential a small loop over matrix*matrix or a matrix*vector multiplication (with funny strides because its convolution). I did this in Python for dx but if you call H*W kernels from python that is actually way slower in all cases I tested.

**Comment by geohot** [comment]
The cones are actually fast. It's the O(n) stuff that's surprisingly slow.

**Comment by ryanneph** [comment]
As far as I know GEMM and FFT convolutions are generally faster than nested looping. FFT has some restrictions on boundary conditions (assumes wrapping boundaries IIRC). GEMM solvers on GPU have been heavily optimized in recent years, such as the one in cuBLAS. But the implementation we have is flexible and likely the smallest. 

I think the binary_ops suffer from fragmented global GPU memory accesses. The most obvious sign is that the indices are not purely based on global thread ids (they contain variable divisors). That is likely issuing 32 memreads per transaction instead of just one of it were coalesced. Global mem access has a huge latency (500-1000 cycles, at least on nvidia hardware), and non-coalesced access has a huge cost.

**Comment by kartik4949** [comment]
> As far as I know GEMM and FFT convolutions are generally faster than nested looping. FFT has some restrictions on boundary conditions (assumes wrapping boundaries IIRC). GEMM solvers on GPU have been heavily optimized in recent years, such as the one in cuBLAS. But the implementation we have is flexible and likely the smallest.
> 
> I think the binary_ops suffer from fragmented global GPU memory accesses. The most obvious sign is that the indices are not purely based on global thread ids (they contain variable divisors). That is likely issuing 32 memreads per transaction instead of just one if it is coalesced. Global mem access has a huge latency (500-1000 cycles, at least on nvidia hardware), and non-coalesced access has a huge cost.
> 
> A naive solution to both broadcasting and memory access speed would be to fill out a full sized tensor on the cpu (before executing the kernel) with duplicated data along axes where broadcasting occurs. This obviously incurs a storage cost, but it would remove the need for variable divisors in the global memory indices, and would enable coalesced memreads. That would optimize all binary ops and give us a short road to broadcasting. There are more elegant options, but we have 11 lines to spare at the moment...

"Direct approach can be faster on some kernel sizes than FFT"

**Comment by marcelbischoff** [comment]
One way to speed up O(n) is to put several O(n) in a single kernel. I am looking at the non first class ops like swish which seems to be used a lot!? Would it make sense to hardcode this in a single kernel?

**Comment by geohot** [comment]
Made it a bit faster by not recreating the kernels, but it's still slow. The dispatch is so expensive!

**Comment by kartik4949** [comment]
just thinking out loud, can __slots__ in Tensor class make a difference?
as it decreases memory footprint and has faster attribute access and normal dict :)
@geohot thoughts??

**Comment by geohot** [comment]
Hmm, this __slots__ is a cool thing to learn about! 

But I don't think that's the slowness, I suspect it's the GPU driver. Want to profile it?

**Comment by kartik4949** [comment]
yeah GPU driver accounts the highest percentage of slowness no doubt....
I was talking about icing on cake :P but I guess lets get the cake first (fix the gpu slowness :))
:), and yeah slots are cool do check them out.

**Comment by iperov** [comment]
check my opencl ML lib https://github.com/iperov/litenn it is only x4 slower than tensorflow

**Comment by geohot** [comment]
#144 is better about this. Let's see if the litenn ops are better?

**Comment by hemangjoshi37a** [comment]
I agree with @ryanneph and @kartik4949 regarding the potential issue with fragmented global GPU memory access. Coalescing memory read/write can indeed result in significant performance improvements. Also, the concept of creating a full-sized tensor on the CPU, as @ryanneph suggested, could be a promising approach, despite the storage overhead.

Furthermore, I'd like to suggest looking into an optimization technique called kernel fusion. It can be highly effective in eliminating overheads caused by multiple kernel invocations. This is particularly beneficial for element-wise operations like Mul, Add, and broadcasting, which seem to be the primary culprits for the current performance issues. 

Here's a simple pseudo-code example of how it could be implemented:

```python
def fused_kernel(a, b, c):
    i = get_global_id(0)
    c[i] = a[i] * b[i] + c[i]
```

By combining multiplication and addition in a single kernel, we can reduce global memory accesses and thus potentially boost the performance.

Incorporating these changes could make GPU performance in tinygrad more efficient, bringing it closer to the goal of having a lean and fast deep learning library. While this does add a few more lines to the code, the trade-off in terms of speed might be worth considering.

Additionally, as @kartik4949 mentioned, Python's `__slots__` can also provide some minor speed improvements. Though it's not a game-changer, it could contribute to the overall efficiency.
