### ISSUE TITLE
Work on YOLOv5 loading

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#235]
Started in examples/yolov5.py

**Comment by kartik4949** [comment]
if we are inventing the wheel again (tinygrad), why not make our own small object detection model which will be flexible and scalable so that it can run in real-time as we have performance issues.
i.e make our own yolo type (single shot detecting)
thoughts?

**Comment by geohot** [comment]
The point of tinygrad is to support all existing modern networks with a very simple library, not create our own.

**Comment by kartik4949** [comment]
Hmm gotcha

**Comment by kartik4949** [comment]
also just thinking out loud, to speedup YOLOv5 inference once it is done, we can do some weight pruning :)

**Comment by MANU-CHAUHAN** [comment]
You may have to cross check Yolo5 once if it is actually any better than V4, as per the claims. There was a controversy about it being a kind of a knock off and improvements could not be as substantial as claimed, YOLO4 still is (in absolute sense) the last upgrade in YOLO series. Please cross check once though. 

I have not analysed in-depth the differences though. Just updating all to cross-check once.

Probably will help:
1) [Youtube](https://www.youtube.com/watch?v=X_jfbXA9mUM)
2) [medium](https://medium.com/swlh/yolov5-controversy-is-yolov5-real-20e048bebb08)

**Comment by geohot** [comment]
Hmm, yolov5 seems better packaged. I doubt it really matters.

**Comment by skoshx** [comment]
@geohot Any work yet on implementing yolov5 model using tinygrad, or should I get to it?

**Comment by geohot** [comment]
Haven't done more than what is committed.

**Comment by skoshx** [comment]
@geohot Alright, I have started trying to implement it. Probably gonna take me ages since the codebase isn't the most readable...

**Comment by AdityaNG** [comment]
I have forked and started working on it too. So far I managed to get torch.load() to work on the YOLOv5 weights.
The unpickling failed as the model seemed to use objects form the original YOLOv5 repo; I've used a slighly hacky solution of copy pasting the required files from the repo. I will see if there is a better way of getting around this, but it fixed the pickling issue and loads in the weights with torch.

https://github.com/AdityaNG/tinygrad/tree/aditya

`print( torch.load(io.BytesIO(dat)) )
`

```
{'epoch': -1, 'best_fitness': array([    0.37143]), 'training_results': None, 'model': Model(
  (model): Sequential(
    (0): Focus(
      (conv): Conv(
        (conv): Conv2d(12, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU()
      )
    )
    .......
    .......
    .......
    (24): Detect(
      (m): ModuleList(
        (0): Conv2d(128, 255, kernel_size=(1, 1), stride=(1, 1))
        (1): Conv2d(256, 255, kernel_size=(1, 1), stride=(1, 1))
        (2): Conv2d(512, 255, kernel_size=(1, 1), stride=(1, 1))
      )
    )
  )
), 'optimizer': None, 'wandb_id': '128df853'}
```

I'll continue working on this and would like to contribute.

**Comment by GeorgeDeac** [comment]
Also see my comment with the released benchmarks, the pytorch yolov4 implementation + deepsort might be better imo (this might also depend a lot on the hardware implementation afterwards though)

**Comment by hemangjoshi37a** [comment]
Reflecting on the challenges faced in the YOLOv5 implementation, I agree with @MANU-CHAUHAN about the importance of critically evaluating the performance of different versions of YOLO. This understanding can not only provide us valuable insights but also improve the tinygrad library's functionality. 

I have been working on a potential solution to address the loading of YOLOv5 weights in tinygrad. The issue of `torch.load()` failing due to the model using objects from the original YOLOv5 repo could be circumvented by dynamically mapping the custom classes from YOLOv5 to native PyTorch equivalents at runtime, thus avoiding the need for adding extra dependencies or altering the structure of our codebase. Here's a simplified example of how this can be done:

```python
import torch
from torchvision.models import resnet

class_map = {
    "YOLOLayer": torch.nn.Module,
    # Add other custom classes here...
}

torch.load("path/to/weights.pt", map_location="cpu", pickle_module=dyn_module)
```

It's still a work in progress, but I believe it could be a step towards a more adaptable approach. 
I'm intrigued by @kartik4949's idea of weight pruning to speed up the YOLOv5 inference. Pruning is indeed a promising approach to reduce computational complexity and improve the efficiency of neural networks.

**Comment by GeorgeDeac** [comment]
I did some research on my own for another project, there are a few cool papers on this if you guys are interested that summarize each incremental update that was made on the yolo architecture:
https://arxiv.org/abs/2304.00501

See the techniques that can be applied on Yolov4:
bag of freebies: https://arxiv.org/abs/2207.02696
and bag of tricks (if we want ReID): https://arxiv.org/abs/1903.07071
