### ISSUE TITLE
test_shapetracker tests failing *challenge*

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#337]
Anyone want a challenge?

Check out TestComplexShapeTracker, those tests are failing but they shouldn't be.

Can you fix them in a few lines?

**Comment by geohot** [comment]
I think it has something to do with reshape and mod

**Comment by Henistein** [comment]
I present here the test that is failing and why:
```python
s = ShapeTracker((4,4)) # strides = (4,1)
s.permute(1,0) # strides = (1,4)
s.reshape(2,2,2,2) # strides = (8,4,2,1)
s.permute(2,3,0,1) # strides = (2,1,8,4)
```
The problem is that after reshaping to (2,2,2,2) the strides should be (2,1,8,4), so when permuting to (2,3,0,1) the final strides would be (8,4,2,1) which is contiguous. In reshape function it must just create a new view if it's contiguous if not it should just update the strides. In this way it should be easier to check the contiguity by checking if the last element of views is contiguous: 
```python
def contiguous(self): return self.views[-1].contiguous
```

**Comment by geohot** [comment]
It's fixed in the chonker branch, just need to upstream.
