### ISSUE TITLE
Support for Coral devices with Edge TPU

### ISSUE THREAD

**Issue by pythops** [geohot/tinygrad#472]
Any plan to support the edge tpu devices ?

**Comment by geohot** [comment]
It's an undocumented very complex custom arch that's totally different from big TPU. Doable, but why, think it's a dead end chip.

**Comment by krzim** [comment]
I think the "why" might be answered with their new MCU with a TPU, Cortex M7, and Cortex M4. So far as I know, it's the only mass produced microcontroller with an ML accelerator built in. `tinygrad` would be a perfect fit on such a device.

What would you need help with in order to make this happen?
