### ISSUE TITLE
0D tensor support: can it happen?

### ISSUE THREAD

**Issue by Joqsan** [geohot/tinygrad#765]
Numpy, PyTorch, etc., provide support for zero-dimensional tensors:

```python
>>> import numpy as np
>>> a = np.array(55)
>>> a.shape, a.ndim
((), 0)
```

plus **0D support** is one of **einops**’ hard requirements to add a framework as a backend (see https://github.com/arogozhnikov/einops/pull/122 and https://github.com/PaddlePaddle/Paddle/issues/34220), if https://github.com/geohot/tinygrad/issues/617 wants to see the light someday.

After looking `tensor.py` and `shapetracker.py` I noticed some code/assertions relying on the underlying shape being a non-0D tensor, as if that was the choice from the beginning.

**Question**: is adding 0D support a task worth undertaking? How to avoid shooting yourself in the foot when trying to do so?

**Comment by geohot** [comment]
I don't think it's too hard. I avoided it, but really shouldn't have. Would merge a clean PR adding it.

**Comment by Joqsan** [comment]
I'll give it a try.

**Comment by hemangjoshi37a** [comment]
Hello @geohot, @Joqsan, The idea of adding 0D tensor support in `tinygrad` is an interesting one and it could align this library more closely with industry standards like Numpy and PyTorch. It also opens up the possibility of integrating with other libraries such as einops, as mentioned, which could potentially broaden the scope and usage of `tinygrad`.

For introducing 0D tensor support, we need to be careful with tensor operations. In 0D tensor cases, the operations should return a scalar value rather than a tensor. Here's a simplified example illustrating the principle:

```python
class Tensor:
    def __init__(self, data):
        self.data = np.array(data)
        self.shape = self.data.shape
        self.ndim = self.data.ndim

    def __add__(self, other):
        result = self.data + other.data
        if result.ndim == 0:
            return result.item() # return scalar value
        else:
            return Tensor(result)
```

This is just a start and more considerations are needed for other tensor operations, especially when it comes to broadcasting and gradients. 

One more thing to watch out for is the backward compatibility. Since the current codebase assumes that all tensors have at least one dimension, it's crucial to ensure that adding 0D tensor support won't break existing functionalities.

**Comment by Joqsan** [comment]
Hi @hemangjoshi37a 

As far I can see the only difference would be with full reductions. For instance, instead of having to do `y.sum().numpy()[0]` we'll just need `y.sum().numpy()`.

**Comment by xl0** [comment]
I'm not sure I follow. Why would we want to return a scalar and not a 0D tensor?

**Comment by geohot** [comment]
Done!
