### ISSUE TITLE
Crusade against `isinstance`

### ISSUE THREAD

**Issue by rayanht** [geohot/tinygrad#810]
Many calls to the expensive function `isinstance` in various hot paths. In the majority of cases we can avoid those calls using inheritance or single-dispatch.

Should be a significant speed up if we manage to eliminate most of them.

**Comment by geohot** [comment]
Can post a related bounty, and I'll lock if for you if you want it.

$500 for <100 ms LLaMA runtime on my machine (AMD EPYC 7662) without the JIT. It's 450ms on my machine now, but nobody has spent any time thinking about this. It's only 50ms on the GPU (and this is async), so there's no bottleneck there.

`DEBUG=1 OPTLOCAL=1 python3 examples/llama.py --prompt "hello" --count 10 --timing`

```
ran model in 571.36 ms, 48.26 ms on GPU      
sync in 1.77 ms                               
.                                                                                                                                                                                                                  
ran model in 567.93 ms, 48.20 ms on GPU
sync in 1.74 ms                                                                                                                                                                                                    
uk                                                                                                       
ran model in 572.91 ms, 48.21 ms on GPU
sync in 1.77 ms        
```

The 450ms is with DEBUG=0, that's the target. It's spending 450ms deciding what to compute, and 50ms actually computing it!

The kernels are all cached by pyopencl, so there shouldn't be time spent compiling them. When I profile by adding `--profile` to that command, then `python3 -c "import pstats; pstats.Stats('out.prof').sort_stats('tottime').print_stats(10)"`

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       70    0.281    0.004    0.282    0.004 /home/tiny/.local/lib/python3.10/site-packages/pyopencl/__init__.py:732(program_build)
91776/84848    0.244    0.000    2.637    0.000 /home/tiny/tinygrad/tinygrad/lazy.py:187(movement_op)
41632/1816    0.243    0.000    2.348    0.001 /home/tiny/tinygrad/tinygrad/lazy.py:107(realize)
    85144    0.234    0.000    4.165    0.000 /home/tiny/tinygrad/tinygrad/tensor.py:19(apply)
    97954    0.226    0.000    0.316    0.000 /home/tiny/tinygrad/tinygrad/shape/shapetracker.py:33(__init__)
    39882    0.223    0.000    0.601    0.000 /home/tiny/tinygrad/tinygrad/shape/shapetracker.py:185(reshape)
  2140972    0.222    0.000    0.222    0.000 {built-in method builtins.isinstance}
    54968    0.193    0.000    0.558    0.000 /home/tiny/tinygrad/tinygrad/lazy.py:88(__init__)
131544/6264    0.180    0.000    0.517    0.000 /usr/lib/python3.10/dataclasses.py:1242(_asdict_inner)
    88272    0.173    0.000    0.585    0.000 /home/tiny/tinygrad/tinygrad/tensor.py:36(__init__)
```

It's in the places you were working on, and 2M calls to isinstance! That program_build is likely caused by a simple bug, it should be caching.

**Comment by hemangjoshi37a** [comment]
Hello @geohot, @rayanht, One way to handle this could be the use of python's `functools.singledispatch` function decorator to perform function overloading based on the first argument's type.

```python
from functools import singledispatch

@singledispatch
def process(obj):
    raise NotImplementedError("Unsupported type")

@process.register
def _(obj: Type1):
    # process for Type1

@process.register
def _(obj: Type2):
    # process for Type2
```
Here, you define a base function that raises a `NotImplementedError` for unsupported types. Then, you register versions of the function for each type you want to support. Python will call the appropriate function based on the type of the first argument.

Nevertheless, replacing `isinstance` completely might require some careful refactoring and testing to ensure that it doesn't inadvertently affect other aspects of the program.
