### ISSUE TITLE
b0c0c5d0d62e40df97999c8df3c1809ecb7842db breaks enet inference on CPU!

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#86]
@ryanneph it just hangs on CPU

**Comment by ryanneph** [comment]
Striding isn't essential at this point so you can revert and I'll look at it.

**Comment by geohot** [comment]
Too many conflicts to revert

**Comment by marcelbischoff** [comment]
Thought I fetched this and it worked on CPU... have to check!

**Comment by ryanneph** [comment]
Here's the stack trace
```
-> out, _ = infer(model, img)
(Pdb) bt
  /usr/lib/python3.8/bdb.py(580)run()
-> exec(cmd, globals, locals)
  <string>(1)<module>()
> /home/ryanneph/tinygrad/examples/efficientnet.py(194)<module>()
-> out, _ = infer(model, img)
  /home/ryanneph/tinygrad/examples/efficientnet.py(150)infer()
-> out = model.forward(Tensor(img))
  /home/ryanneph/tinygrad/examples/efficientnet.py(93)forward()
-> x = block(x)
  /home/ryanneph/tinygrad/examples/efficientnet.py(52)__call__()
-> x_squeezed = x.avg_pool2d(kernel_size=x.shape[2:4])
  /home/ryanneph/tinygrad/tinygrad/tensor.py(187)dispatch()
-> return f.apply(f, self, *x, **kwargs)
  /home/ryanneph/tinygrad/tinygrad/tensor.py(175)apply()
-> ret = Tensor(op.forward(ctx, *[t.data for t in x], **kwargs))
  /home/ryanneph/tinygrad/tinygrad/ops.py(286)forward()
-> stack, (my, mx) = stack_for_pool(x, kernel_size, stride, fill_value=np.nan)
  /home/ryanneph/tinygrad/tinygrad/ops.py(243)stack_for_pool()
-> stack = fill_value*np.ones((ky, kx, *x.shape[:2], my+ky, mx+kx), dtype=x.dtype)
  /home/ryanneph/tinygrad/venv/lib/python3.8/site-packages/numpy/core/numeric.py(193)ones()
-> multiarray.copyto(a, 1, casting='unsafe')
  <__array_function__ internals>(5)copyto()
```
Looking into a fix. We should add a test for enet inference to catch this in the future.

**Comment by ryanneph** [comment]
Kernel_size being fed to avgpool2d is (112,112) which is same as x.shape[2:] - this looks like avgpool2d is being used for a global average pooling operation by setting a large kernel_size.

This results in allocation of a HUGE array buffer and reveals an issue with the stack_for_pool approach to implementing pooling ops. Iteration-based pooling, like the one used in GPU would be preferred to limit memory usage for large kernel_sizes. 

I've reverted all of my changes to the CPU pooling ops in [https://github.com/ryanneph/tinygrad/tree/revert_#74](https://github.com/ryanneph/tinygrad/tree/revert_%2374) and I've submitted a reversion PR (#87) to fix for now. Actually this shows that the original CPU pooling ops fail for many kernel sizes, even without separate striding, since the original pooling op was only tested for kernel_size=(2,2).

Long term, we can leave the existing stack_for_pooling-based CPU pooling ops for standard pooling (small kernel size) and implement a separate global average pooling op instead based on iteration to handle this inefficiency.

**Comment by ryanneph** [comment]
nvm, it's not global avg pooling, it's adaptive average pooling. That explains why kernel_size is so large, since its actually the pooling output size. So based on that, instead of reverting b0c0b5d, we can just replace:
efficientnet.py:52
```x.avg_pool2d(kernel_size=x.shape[2:4])``` 
with 
```x.avg_pool2d(kernel_size(1,1)```

That gives output cock instead of hen with my CPU Pooling ops, which we could argue is more accurate for 
```python3 examples/efficientnet.py https://upload.wikimedia.org/wikipedia/commons/4/41/Chicken.jpg```
